// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``` 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiwV5O2A_EiNYMWZlrueTv5qzIJtmLs80',
    appId: '1:743583037554:web:758181b1d18a6cfb012aeb',
    messagingSenderId: '743583037554',
    projectId: 'findme-938c1',
    authDomain: 'findme-938c1.firebaseapp.com',
    storageBucket: 'findme-938c1.appspot.com',
    measurementId: 'G-PQYDYH90CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-duoHdxb74vZO84_bqkTf7WRXIPPHgVU',
    appId: '1:743583037554:android:4c0e7c4dce1be575012aeb',
    messagingSenderId: '743583037554',
    projectId: 'findme-938c1',
    storageBucket: 'findme-938c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwmIdgR2nQRciXMgC5an1saGxngKmyBiw',
    appId: '1:743583037554:ios:206b0a59c361cb19012aeb',
    messagingSenderId: '743583037554',
    projectId: 'findme-938c1',
    storageBucket: 'findme-938c1.appspot.com',
    iosBundleId: 'com.example.findme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwmIdgR2nQRciXMgC5an1saGxngKmyBiw',
    appId: '1:743583037554:ios:206b0a59c361cb19012aeb',
    messagingSenderId: '743583037554',
    projectId: 'findme-938c1',
    storageBucket: 'findme-938c1.appspot.com',
    iosBundleId: 'com.example.findme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiwV5O2A_EiNYMWZlrueTv5qzIJtmLs80',
    appId: '1:743583037554:web:360943643b091038012aeb',
    messagingSenderId: '743583037554',
    projectId: 'findme-938c1',
    authDomain: 'findme-938c1.firebaseapp.com',
    storageBucket: 'findme-938c1.appspot.com',
    measurementId: 'G-R0TYP4HSQG',
  );

}